[versions]
detektVersion = "1.23.5"
androidAppCompatVersion = "1.6.1"
androidSocketIoVersion = "2.1.0"
kotlinxSerializationVersion = "1.6.3"
mokoSocketIoVersion = "0.4.0"
compileSdk = "33"
targetSdk = "33"
minSdk = "16"

[libraries]
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompatVersion" }
socketIo = { module = "io.socket:socket.io-client", version.ref = "androidSocketIoVersion" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
mokoSocketIo = { module = "dev.icerock.moko:socket-io", version.ref = "mokoSocketIoVersion" }
detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektVersion" }

